# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  migrator:
    image: rey/starworks:latest
    environment:
      NODE_ENV: production
    env_file:
      - .env
    command: ['npm', 'run', 'migrate:up']
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - tools

  server:
    image: rey/starworks:latest
    environment:
      NODE_ENV: production
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    volumes:
      - ./db-data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
