CREATE TABLE IF NOT EXISTS `auth` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT(20) UNSIGNED NOT NULL,
    `user_agent` VARCHAR(255) NOT NULL,
    `logged_in_at` TIMESTAMP NOT NULL,
    `is_expired` TINYINT(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`) USING BTREE,
    CONSTRAINT `auth_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE = InnoDB;